# Generated by Django 5.2.1 on 2025-05-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solire_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='timestamp',
            new_name='timestamps',
        ),
        migrations.RenameField(
            model_name='moisture',
            old_name='timestamp',
            new_name='timestamps',
        ),
        migrations.RenameField(
            model_name='ph',
            old_name='timestamp',
            new_name='timestamps',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='timestamp',
            new_name='timestamps',
        ),
    ]
