# Generated by Django 5.2.1 on 2025-05-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solire_app', '0002_rename_timestamp_color_timestamps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ph_value', models.FloatField()),
                ('temperature_value', models.IntegerField()),
                ('moisture_value', models.IntegerField()),
                ('rgb_value', models.IntegerField()),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Moisture',
        ),
        migrations.DeleteModel(
            name='Ph',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
