# Generated by Django 5.2.1 on 2025-06-09 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solire_app', '0003_soilcondition_delete_color_delete_moisture_delete_ph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilcondition',
            name='rgb_value',
        ),
    ]
