# Generated by Django 5.2.1 on 2025-08-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solire_app', '0004_remove_soilcondition_rgb_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilcondition',
            name='temperature_value',
            field=models.FloatField(),
        ),
    ]
