# Generated by Django 5.2.1 on 2025-08-05 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solire_app', '0005_alter_soilcondition_temperature_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilcondition',
            name='timestamps',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 5, 9, 38, 81434, tzinfo=datetime.timezone.utc)),
        ),
    ]
