# Generated by Django 5.2.1 on 2025-08-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solire_app', '0006_alter_soilcondition_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilcondition',
            name='timestamps',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
